# Generated by Django 4.2.5 on 2023-09-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_like_rating_delete_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='is_liked',
            new_name='is_like',
        ),
    ]
